mandatory:
  blog_name: "Docsie.io Blog"
  landing_name: ""
  landing_description: ""
  landing_image: ""
  theme: "tailwind_g"
  template: "tailwind_g"
  blog_root_url: "blog"
  url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vR2Unb1VTOB1upja915Rp7N6MJnqtLLOPYUlrJW7R0qybH_kGWB1wPozgjAf6X5JD-Bv_XldO9yKSLU/pub?output=csv"
  domain_url: ""
optional:
  link_menu:
    - link: "https://www.docsie.io"
      text: "Docsie"
    - link: "https://www.docsie.io/pricing/"
      text: "Docsie Pricing"
    - link: "https://www.docsie.io/try_docsie/"
      text: "Try Docsie"

  search_config:
    title:
      weight: 8
    summary:
      weight: 6
    author_name:
      weight: 5
    categories:
      weight: 3

  comments:
    enabled: true
    commentbox_project_id: "5725910686760960-proj"

  subscribe:
    enabled: true
    title: "Subscribe to the newsletter"
    summary: "Stay up to date with our latest news and products"
    button_text: "Subscribe"
