# mandatory
blog_name: "Docsie.io Blog"
blog_root_url: "blog"
blog_post_location_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vR2Unb1VTOB1upja915Rp7N6MJnqtLLOPYUlrJW7R0qybH_kGWB1wPozgjAf6X5JD-Bv_XldO9yKSLU/pub?output=csv"
domain_url: ""

# optional
link_menu:
  - link: "https://www.docsie.io"
    text: "Docsie"
  - link: "https://www.docsie.io/pricing/"
    text: "Docsie Pricing"
  - link: "https://www.docsie.io/try_docsie/"
    text: "Try Docsie"

search_config:
  title:
    weight: 8
  summary:
    weight: 6
  author_name:
    weight: 5
  categories:
    weight: 3

comments:
  enabled: true
  commentbox_project_id: "5725910686760960-proj"

google_tag_manager:
  enabled: false
  google_tag_manager_projectid: "GTM-TZRGMQ!"

subscribe:
  enabled: true
  title: "Subscribe to the newsletter"
  summary: "Stay up to date with our latest news and products"
  button_text: "Subscribe"

sharect:
  enabled: true
  twitter: true
  facebook: true
  twitterUsername: ""
  backgroundColor: "#333333"
  iconColor: "#FFFFFF"
  selectableElements:
    - body

landing_meta:
  title: ""
  description: ""
  image: ""
  keywords: ""
  url: ""
  author: ""

translate_articles: false  # defaults to false
show_language_picker: true

google_translator:
  api_key: <api key>

deepl_translator:
  api_key: <api key>

translation_list:
  -
    abbreviation: de
    label: Deutsch
  -
    abbreviation: ru
    label: Русский

source_language:
  abbreviation: en
  label: English


translator: deepl # or google
# User should select an available translator or get warned if `translate_articles` is set to true, but translator is not.

favicons:
  -
    rel: icon
    sizes: 32x32
    type: image/png
    path: favicon.ico
